### ISSUE TITLE
auto configuration optional dependencies

### ISSUE THREAD

**Issue by yungez** [Microsoft/azure-spring-boot-starters#51]
- auto configuration optional dependencies - per the guidelines (  https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-developing-auto-configuration.html ) it can be advisable to express dependencies from autoconfig pom as optional. This can allow the autoconfig code to be included on the class path and it will be ‘harmless’ if the dependant jar is not there ( see 44.4.2 in that doc). In your case I see the dependency from the servicebus autoconfig pom onto the azure-servicebus jar as currently non optional.

- related to that you don’t necessarily actually need a starter jar if there aren’t lots of other dependencies to include.  See section 44.4 of that document. If all your starter pom does is point at the auto configuration jar (servicebus starter pom, for example) then you could choose just to have the auto configure jar. (the servicebus starter does this: https://github.com/Microsoft/azure-spring-boot-starters/blob/master/azure-servicebus-spring-boot-starter/pom.xml ). This is only a suggestion though.

**Comment by ZhijunZhao** [comment]
Regarding the suggestion about optional dependencies, we would need to add the azure-servicebus jar dependency to the starter pom if making it optional in the autoconfig pom. Although both of these two modules are released, our intention is to let user use the starter module. So, making the change wouldn’t provide any benefit to end users. 

On the other side, spring-boot-autoconfigure module auto-configures for a lot of starters, instead of one. So, this is the case that optional dependency is necessary.
