### ISSUE TITLE
Typo in screenshot of documentation

### ISSUE THREAD

**Issue by zhzy0077** [Microsoft/azure-spring-boot-starters#79]
![application.properties](https://docs.microsoft.com/en-us/azure/cosmos-db/media/documentdb-java-spring-boot-starter-with-cosmos-db/re02.png)
Missing space between "the" and "name" in documentation.

**Comment by zhzy0077** [comment]
Also, can we use placeholder as keys and uri ?

**Comment by rmcmurray** [comment]
I fixed the image, and I will be checking that in shortly.

I typically prefer not to use placeholders for values because some customers have misinterpreted *placeholders* as *variables*, which they assume are coming from somewhere else, so we get questions about that. Because of their confusion, I prefer to use example values when possible.
